/*
 * Copyright (c) 2022 New Vector Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package im.vector.app.features.pin.lockscreen.crypto

import android.content.Context
import android.os.Build
import android.security.keystore.KeyGenParameterSpec

/**
 * Class in charge of managing both the PIN code key and the system authentication keys.
 */
class LockScreenKeyRepository(
        private val context: Context,
        private val baseName: String,
) {

    private val pinCodeKeyAlias: String get() {
        // If there was a previous key generated by the old lib we need to keep using it since KeyStore doesn't allow renaming.
        return if (KeyStoreCrypto.containsKey(LEGACY_PIN_CODE_KEY_ALIAS)) {
            LEGACY_PIN_CODE_KEY_ALIAS
        } else {
            "$baseName.pin_code"
        }
    }

    private val systemKeyAlias = "$baseName.system"

    /**
     * Get the key associated to the PIN code. It will be created if it didn't exist before.
     */
    fun getPinCodeKey(): KeyStoreCrypto = getKeyStoreCrypto(pinCodeKeyAlias)

    /**
     * Get the key associated to the system authentication (biometrics). It will be created if it didn't exist before.
     * Note: this key will be invalidated by new biometric enrollments.
     */
    fun getSystemKey(keyGenParameterSpecBuilder: (KeyGenParameterSpec.Builder.() -> Unit)? = null): KeyStoreCrypto =
        getKeyStoreCrypto(systemKeyAlias, keyGenParameterSpecBuilder = keyGenParameterSpecBuilder ?: {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                setUserAuthenticationRequired(true)
            }
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                setInvalidatedByBiometricEnrollment(true)
            }
        })

    /**
     * Returns if the PIN code key already exists.
     */
    fun hasPinCodeKey() = KeyStoreCrypto.containsKey(pinCodeKeyAlias)

    /**
     * Returns if the system authentication key already exists.
     */
    fun hasSystemKey() = KeyStoreCrypto.containsKey(systemKeyAlias)

    /**
     * Deletes the PIN code key from the KeyStore.
     */
    fun deletePinCodeKey() = KeyStoreCrypto.deleteKey(pinCodeKeyAlias)

    /**
     * Deletes the system authentication key from the KeyStore.
     */
    fun deleteSystemKey() = KeyStoreCrypto.deleteKey(systemKeyAlias)

    /**
     * Checks if the current system authentication key exists and is valid.
     */
    fun isSystemKeyValid() = hasSystemKey() && getSystemKey().hasValidKey()

    /**
     * Is using legacy key for PIN code.
     */
    fun isUsingLegacyPinCodeKey() = pinCodeKeyAlias == LEGACY_PIN_CODE_KEY_ALIAS

    /**
     * As we support Android APIs >= 21 we need to add a 'legacy' KeyStoreCrypto for devices in APIs < 23 where the new cryptographic APIs were added.
     */
    private fun getKeyStoreCrypto(alias: String, keyGenParameterSpecBuilder: KeyGenParameterSpec.Builder.() -> Unit = {}): KeyStoreCrypto =
            KeyStoreCryptoCompat.create(context, alias, keyGenParameterSpecBuilder).also { it.initialize() }

    companion object {
        internal const val LEGACY_PIN_CODE_KEY_ALIAS = "fp_pin_lock_screen_key_store"
    }
}
